#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env"

# shellcheck source=scripts/backend_process_lib.sh
source "${ROOT_DIR}/scripts/backend_process_lib.sh"

BACKEND_ENV_ALLOWED_KEYS=(
  API_PORT
  API_BASE_URL
  CODEX_COMMAND
  CODEX_USE_EXEC
  CODEX_EXEC_ARGS
  CODEX_RESUME_ARGS
  CODEX_WORKDIR
  PROJECTS_ROOT
  CHAT_STORE_PATH
  FEEDBACK_QUEUE_PATH
  FEEDBACK_IMAGE_DIR
  FEEDBACK_AUDIO_DIR
  ASSET_DEPOT_DIR
  PROJECT_FACTORY_STATE_DIR
  BRIDGE_ENVIRONMENT
  BRIDGE_STAGE_ID
  BRIDGE_SPEC_ID
  BRIDGE_STAGE_BRANCH
  BRIDGE_STAGE_WORKTREE_PATH
  BRIDGE_APP_CHANNEL
  BRIDGE_UPDATER_CHANNEL
  BRIDGE_APP_LABEL
  BRIDGE_ENVIRONMENT_COLOR
  DEV_PIPELINE_STATE_PATH
  DEV_PIPELINE_RUNTIME_ROOT
)
backend_export_env_file_values "${ENV_FILE}" "${BACKEND_ENV_ALLOWED_KEYS[@]}"

PYTHON_BIN="python3"
if [[ -x "${ROOT_DIR}/.venv/bin/python" ]]; then
  PYTHON_BIN="${ROOT_DIR}/.venv/bin/python"
fi

cd "${ROOT_DIR}"
exec env \
  API_PORT="${API_PORT:-}" \
  API_BASE_URL="${API_BASE_URL:-}" \
  CODEX_COMMAND="${CODEX_COMMAND:-}" \
  CODEX_USE_EXEC="${CODEX_USE_EXEC:-}" \
  CODEX_EXEC_ARGS="${CODEX_EXEC_ARGS:-}" \
  CODEX_RESUME_ARGS="${CODEX_RESUME_ARGS:-}" \
  CODEX_WORKDIR="${CODEX_WORKDIR:-}" \
  PROJECTS_ROOT="${PROJECTS_ROOT:-}" \
  CHAT_STORE_PATH="${CHAT_STORE_PATH:-}" \
  FEEDBACK_QUEUE_PATH="${FEEDBACK_QUEUE_PATH:-}" \
  FEEDBACK_IMAGE_DIR="${FEEDBACK_IMAGE_DIR:-}" \
  FEEDBACK_AUDIO_DIR="${FEEDBACK_AUDIO_DIR:-}" \
  ASSET_DEPOT_DIR="${ASSET_DEPOT_DIR:-}" \
  PROJECT_FACTORY_STATE_DIR="${PROJECT_FACTORY_STATE_DIR:-}" \
  BRIDGE_ENVIRONMENT="${BRIDGE_ENVIRONMENT:-}" \
  BRIDGE_STAGE_ID="${BRIDGE_STAGE_ID:-}" \
  BRIDGE_SPEC_ID="${BRIDGE_SPEC_ID:-}" \
  BRIDGE_STAGE_BRANCH="${BRIDGE_STAGE_BRANCH:-}" \
  BRIDGE_STAGE_WORKTREE_PATH="${BRIDGE_STAGE_WORKTREE_PATH:-}" \
  BRIDGE_APP_CHANNEL="${BRIDGE_APP_CHANNEL:-}" \
  BRIDGE_UPDATER_CHANNEL="${BRIDGE_UPDATER_CHANNEL:-}" \
  BRIDGE_APP_LABEL="${BRIDGE_APP_LABEL:-}" \
  BRIDGE_ENVIRONMENT_COLOR="${BRIDGE_ENVIRONMENT_COLOR:-}" \
  DEV_PIPELINE_STATE_PATH="${DEV_PIPELINE_STATE_PATH:-}" \
  DEV_PIPELINE_RUNTIME_ROOT="${DEV_PIPELINE_RUNTIME_ROOT:-}" \
  "${PYTHON_BIN}" main.py
