from __future__ import annotations

import sys
import time
import json


def main() -> int:
    if len(sys.argv) < 2:
        print("Missing message.", file=sys.stderr)
        return 1

    message = sys.argv[-1]

    if message.startswith("sleep:"):
        _, raw_seconds = message.split(":", maxsplit=1)
        time.sleep(float(raw_seconds))
        print(f"Completed after {raw_seconds}s")
        return 0

    if message.startswith("fail:"):
        _, failure_message = message.split(":", maxsplit=1)
        print(failure_message or "Forced failure", file=sys.stderr)
        return 1

    if "/dev-handoff preparation capability" in message:
        print(
            "HANDOFF_JSON "
            + json.dumps(
                {
                    "title": "LLM prepared bridge handoff",
                    "problem": "PROD needs a reviewed DEV handoff generated from the chat.",
                    "context": "The user activated /dev-handoff and wants the LLM to prepare the real spec before queueing.",
                    "acceptance_criteria": "- Draft is generated by LLM\n- Queue is user approved\n- DEV receives tasks",
                    "proposed_spec": "001-llm-prepared-bridge-handoff",
                    "proposed_plan": "01-llm-handoff",
                    "proposed_tasks": [
                        "Persist an LLM-generated draft in PROD state.",
                        "Show the generated draft for user review.",
                        "Queue the approved draft to DEV exactly once.",
                    ],
                    "regression_tests": [
                        "pytest tests/test_dev_pipeline.py -k handoff",
                        "flutter test test/dev_handoff_dialog_test.dart",
                    ],
                    "risks": ["Queueing without explicit user approval."],
                    "evidence": [
                        {
                            "kind": "chat_context",
                            "text": "Generated from the active PROD chat.",
                        }
                    ],
                }
            )
        )
        return 0

    print(f"Codex response: {message}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
